<?php
//  ------------------------------------------------------------------------ //
//                XOOPS - PHP Content Management System                      //
//                    Copyright (c) 2000 XOOPS.org                           //
//                       <http://www.xoops.org/>                             //
// ------------------------------------------------------------------------- //
//  This program is free software; you can redistribute it and/or modify     //
//  it under the terms of the GNU General Public License as published by     //
//  the Free Software Foundation; either version 2 of the License, or        //
//  (at your option) any later version.                                      //
//                                                                           //
//  You may not change or alter any portion of this comment or credits       //
//  of supporting developers from this source code or any supporting         //
//  source code which is considered copyrighted (c) material of the          //
//  original comment or credit authors.                                      //
//                                                                           //
//  This program is distributed in the hope that it will be useful,          //
//  but WITHOUT ANY WARRANTY; without even the implied warranty of           //
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            //
//  GNU General Public License for more details.                             //
//                                                                           //
//  You should have received a copy of the GNU General Public License        //
//  along with this program; if not, write to the Free Software              //
//  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA //
//  ------------------------------------------------------------------------ //

	//include_once XOOPS_ROOT_PATH.'/modules/debaser/include/functions.php';
	global $xoopsUser, $xoopsModuleConfig, $xoopsDB, $xoopsConfig;

	$modversion['name'] = 'debaser';
	$modversion['version'] = 3.08;
	$modversion['description'] = _MI_DEBASER_DESC;
	$modversion['author'] = "frankblack";
	$modversion['credits'] = '';
	$modversion['help'] = "";
	$modversion['license'] = "GPL see LICENSE";
	$modversion['official'] = 0;
	$modversion['image'] = "images/debaser_slogo.png";
	$modversion['dirname'] = 'debaser';

	// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
	// All tables should not have any prefix!
	$modversion['sqlfile']['mysql'] = "sql/mysql.sql";

	// Tables created by sql file (without prefix!)
	$modversion['tables'][0] = 'debaser_files';
	$modversion['tables'][1] = 'debaser_player';
	$modversion['tables'][2] = 'debaservotedata';
	$modversion['tables'][3] = 'debaser_user';
	$modversion['tables'][4] = 'debaser_genre';
	$modversion['tables'][5] = 'debaser_mimetypes';
	$modversion['tables'][6] = 'debaserradio';
	$modversion['tables'][7] = 'debaser_text';
	$modversion['tables'][8] = 'debaser_broken';
	$modversion['tables'][9] = 'debaser_tv';

	// Admin things
	$modversion['hasAdmin'] = 1;
	$modversion['adminindex'] = "admin/index.php";
	$modversion['adminmenu'] = "admin/menu.php";

	// Menu
	$modversion['hasMain'] = 1;

	$module_handler =& xoops_gethandler('module');
	$module =& $module_handler->getByDirname('debaser');
	$groups = (is_object($xoopsUser)) ? $xoopsUser->getGroups() : XOOPS_GROUP_ANONYMOUS;

	if (!is_object($module)) {
		// do nothing - seems to be not installed yet
	} else {

		if (@array_intersect($xoopsModuleConfig['allowupload'], $groups)) {
			if (@array_intersect($xoopsModuleConfig['allowflashupload'], $groups)) {
				$result = $xoopsDB->query("SELECT flashupload FROM ".$xoopsDB->prefix('debaser_user')." WHERE debuid = ".intval($xoopsUser->getVar('uid'))."");
				$hassetting = $xoopsDB->getRowsNum($result);

				if ($hassetting == 1) {
					list($flashupload) = $xoopsDB->fetchRow($result);

					if ($hassetting == $flashupload) $modversion['sub'][] = array('name' => _MI_DEBASER_SUBMITFILE, 'url' => 'uploadflash.php');
					else $modversion['sub'][] = array('name' => _MI_DEBASER_SUBMITFILE, 'url' => 'uploading.php');

		} else {
			$modversion['sub'][] = array('name' => _MI_DEBASER_SUBMITFILE, 'url' => 'uploadflash.php');
		}
		} else {
			$modversion['sub'][] = array('name' => _MI_DEBASER_SUBMITFILE, 'url' => 'uploading.php');
		}
	}

	if (@array_intersect($xoopsModuleConfig['submitlink'], $groups)) $modversion['sub'][] = array('name' => _MI_DEBASER_SUBMITLINK, 'url' => 'uploadinglink.php');

	if (is_object($xoopsUser) && (@array_intersect($xoopsModuleConfig['allowflashupload'], $groups) || @array_intersect($xoopsModuleConfig['allowplaylist'], $groups))) $modversion['sub'][] = array('name' => _MI_DEBASER_MYSETTINGS, 'url' => 'mysetting.php?op=mysettings');

	if (@array_intersect($xoopsModuleConfig['allowplaylist'], $groups)) $modversion['sub'][] = array('name' => _MI_DEBASER_MYPLAYLIST, 'url' => 'mysetting.php?op=playlist');

	}


// Comments
	$modversion['hasComments'] = 1;
	$modversion['comments']['itemName'] = 'id';
	$modversion['comments']['pageName'] = 'singlefile.php';

	// Search
	$modversion['hasSearch'] = 1;
	$modversion['search']['file'] = "include/search.inc.php";
	$modversion['search']['func'] = "debaser_search";

	// Templates
	$modversion['templates'][] = array('file' => 'debaser_uploading.html', 'description' => '');
	$modversion['templates'][] = array('file' => 'debaser_player.html', 'description' => '');
	$modversion['templates'][] = array('file' => 'debaser_index.html', 'description' => '');
	$modversion['templates'][] = array('file' => 'debaser_genre.html', 'description' => '');
	$modversion['templates'][] = array('file' => 'debaser_singlefile.html', 'description' => '');
	$modversion['templates'][] = array('file' => 'debaser_mydebaser.html', 'description' => '');
	$modversion['templates'][] = array('file' => 'debaser_fileedit.html', 'description' => '');
	$modversion['templates'][] = array('file' => 'debaser_admin_menu.html', 'description' => '');
	$modversion['templates'][] = array('file' => 'debaser_radiopopup.html', 'description' => '');
	$modversion['templates'][] = array('file' => 'debaser_tvpopup.html', 'description' => '');
	$modversion['templates'][] = array('file' => 'debaser_uploadlink.html', 'description' => '');
	$modversion['templates'][] = array('file' => 'debaser_uploadflash.html', 'description' => '');
	$modversion['templates'][] = array('file' => 'debaser_broken.html', 'description' => '');
	$modversion['templates'][] = array('file' => 'debaser_search.html', 'description' => '');

	// Blocks
	$modversion['blocks'][] = array(
		'file' => 'debaser_blocks.php',
		'name' => _MI_DEBASER_LATEST,
		'description' => '',
		'show_func' => 'b_debaser_latest_show',
		'edit_func' => 'b_debaser_latest_edit',
		'options' => '5',
		'template' => 'debaser_block_latest.html');
	$modversion['blocks'][] = array(
		'file' => 'debaser_blocks.php',
		'name' => _MI_DEBASER_RATED,
		'description' => '',
		'show_func' => 'b_debaser_rated_show',
		'edit_func' => 'b_debaser_rated_edit',
		'options' => '5',
		'template' => 'debaser_block_rated.html');
	$modversion['blocks'][] = array(
		'file' => 'debaser_blocks.php',
		'name' => _MI_DEBASER_HITS,
		'description' => '',
		'show_func' => 'b_debaser_hits_show',
		'edit_func' => 'b_debaser_hits_edit',
		'options' => '5',
		'template' => 'debaser_block_hits.html');
	$modversion['blocks'][] = array(
		'file' => 'debaser_blocks.php',
		'name' => _MI_DEBASER_VIEWS,
		'description' => '',
		'show_func' => 'b_debaser_views_show',
		'edit_func' => 'b_debaser_views_edit',
		'options' => '5',
		'template' => 'debaser_block_views.html');
	$modversion['blocks'][] = array(
		'file' => 'displatest.php',
		'name' => _MI_DEBASER_DISPLATEST,
		'description' => '',
		'show_func' => 'b_debaser_displatest_show',
		'template' => 'debaser_block_displatest.html');
	$modversion['blocks'][] = array(
		'file' => 'disprated.php',
		'name' => _MI_DEBASER_DISPRATED,
		'description' => '',
		'show_func' => 'b_debaser_disprated_show',
		'template' => 'debaser_block_disprated.html');
	$modversion['blocks'][] = array(
		'file' => 'dispfeature.php',
		'name' => _MI_DEBASER_DISPFEATURED,
		'description' => '',
		'show_func' => 'b_debaser_dispfeatured_show',
		'edit_func' => 'b_debaser_dispfeatured_edit',
		'options' => '150|160|1',
		'template' => 'debaser_block_dispfeatured.html');
	$modversion['blocks'][]= array(
		'file' => 'dispdown.php',
		'name' => _MI_DEBASER_DISPDOWN,
		'description' => '',
		'show_func' => 'b_debaser_dispdown_show',
		'template' => 'debaser_block_dispdown.html');
	$modversion['blocks'][] = array(
		'file' => 'dispviewed.php',
		'name' => _MI_DEBASER_DISPVIEWED,
		'description' => '',
		'show_func' => 'b_debaser_dispviewed_show',
		'template' => 'debaser_block_dispviewed.html');
	$modversion['blocks'][] = array(
		'file' => 'debaser_blocks.php',
		'name' => _MI_DEBASERRAD_TITLE,
		'description' => '',
		'show_func' => 'debaser_showradio',
		'template' => 'radioselect.html');
	$modversion['blocks'][] = array(
		'file' => 'debaser_blocks.php',
		'name' => _MI_DEBASERTV_TITLE,
		'description' => '',
		'show_func' => 'debaser_showtv',
		'template' => 'tvselect.html');
	$modversion['blocks'][] = array(
		'file' => 'debaser_blocks.php',
		'name' => _MI_DEBASER_PLAYLISTBLOCK,
		'description' => '',
		'show_func' => 'debaser_playlistblock',
		'template' => 'debaser_block_playlist.html');
	$modversion['blocks'][] = array(
		'file' => 'debaser_blocks.php',
		'name' => _MI_DEBASER_EQUALIZERBLOCK,
		'description' => '',
		'show_func' => 'debaser_equalizerblock',
		'template' => 'debaser_block_equalizer.html');

//reads the upload_max_size from php.ini - this is not always exact when you come close to outer limit so I cut of 1024 bytes
	$uploadmax = (@ini_get('upload_max_filesize') * 1048576 - 1024);

	//Config settings
	$modversion['config'][] = array(
		'name' => 'uselame',
		'title' => '_MI_DEBASER_USELAME',
		'description' => '_MI_DEBASER_USELAMEDSC',
		'formtype' => 'yesno',
		'valuetype' => 'int',
		'default' => '0');
	$modversion['config'][] = array(
		'name' => 'uselamesingleup',
		'title' => '_MI_DEBASER_USELAMESING',
		'description' => '_MI_DEBASER_USELAMESINGDSC',
		'formtype' => 'yesno',
		'valuetype' => 'int',
		'default' => '0');
	$modversion['config'][] = array(
		'name' => 'pathtolame',
		'title' => '_MI_DEBASER_PATHTOLAME',
		'description' => '_MI_DEBASER_PATHTOLAMEDSC',
		'formtype' => 'textbox',
		'valuetype' => 'text',
		'default' => '');
	$modversion['config'][] = array(
		'name' => 'resampleto',
		'title' => '_MI_DEBASER_RESAMPLETO',
		'description' => '_MI_DEBASER_RESAMPLETODSC',
		'formtype' => 'textbox',
		'valuetype' => 'text',
		'default' => '');
	$modversion['config'][] = array(
		'name' => 'loficondition',
		'title' => '_MI_DEBASER_COND',
		'description' => '_MI_DEBASER_CONDDSC',
		'formtype' => 'select',
		'valuetype' => 'text',
		'default' => '',
		'options' => array('_MI_DEBASER_CONDGROUP' => 'group', '_MI_DEBASER_CONDRANK' => 'rank', '_MI_DEBASER_CONDPOSTS' => 'posts')
		);
	$modversion['config'][] = array(
		'name' => 'loficondcode',
		'title' => '_MI_DEBASER_CONDCODE',
		'description' => '',
		'formtype' => 'textbox',
		'valuetype' => 'text',
		'default' => '');
	$modversion['config'][] = array(
		'name' => 'useffmpeg',
		'title' => '_MI_DEBASER_USEFFMPEG',
		'description' => '_MI_DEBASER_USEFFMPEGDSC',
		'formtype' => 'yesno',
		'valuetype' => 'int',
		'default' => '0');
	$modversion['config'][] = array(
		'name' => 'useffmpegsingleup',
		'title' => '_MI_DEBASER_USEFFMPEGSING',
		'description' => '_MI_DEBASER_USEFFMPEGSINGDSC',
		'formtype' => 'yesno',
		'valuetype' => 'int',
		'default' => '0');
	$modversion['config'][] = array(
		'name' => 'pathtoffmpeg',
		'title' => '_MI_DEBASER_PATHTOFFMPEG',
		'description' => '',
		'formtype' => 'textbox',
		'valuetype' => 'text',
		'default' => '');
	$modversion['config'][] = array(
		'name' => 'ffmpegframes',
		'title' => '_MI_DEBASER_FFMPEGFRAMES',
		'description' => '_MI_DEBASER_FFMPEGFRAMESDSC',
		'formtype' => 'textbox',
		'valuetype' => 'text',
		'default' => '5% 10% 15% 20% 25%');
	$modversion['config'][] = array(
		'name' => 'ffmpegdelay',
		'title' => '_MI_DEBASER_FFMPEGDELAY',
		'description' => '_MI_DEBASER_FFMPEGDELAYDSC',
		'formtype' => 'textbox',
		'valuetype' => 'text',
		'default' => '100');
	$modversion['config'][] = array(
		'name' => 'ffmpegthumbsize',
		'title' => '_MI_DEBASER_FFMPEGTHUMBSIZE',
		'description' => '_MI_DEBASER_FFMPEGTHUMBSIZEDSC',
		'formtype' => 'textbox',
		'valuetype' => 'text',
		'default' => '200x120');
	$modversion['config'][] = array(
		'name' => 'ffmpegtypes',
		'title' => '_MI_DEBASER_FFMPEGTYPES',
		'description' => '_MI_DEBASER_FFMPEGTYPESDSC',
		'formtype' => 'textarea',
		'valuetype' => 'text',
		'default' => 'avi flv');
	$modversion['config'][] = array(
		'name' => 'allowupload',
		'title' => '_MI_DEBASER_ALLOWUPLOAD',
		'description' => '_MI_DEBASER_ALLOWUPLOADDSC',
		'formtype' => 'group_multi',
		'valuetype' => 'array',
		'default' => array('1' => 1));
	$modversion['config'][] = array(
		'name' => 'allowflashupload',
		'title' => '_MI_DEBASER_ALLOWFLASHUPLOAD',
		'description' => '_MI_DEBASER_ALLOWFLASHUPLOADDSC',
		'formtype' => 'group_multi',
		'valuetype' => 'array',
		'default' => '');
	$modversion['config'][] = array(
		'name' => 'submitlink',
		'title' => '_MI_DEBASER_SUBMITLINK',
		'description' => '_MI_DEBASER_SUBMITLINKDSC',
		'formtype' => 'group_multi',
		'valuetype' => 'array',
		'default' => array('1' => 1));
	$modversion['config'][] = array(
		'name' => 'allowplaylist',
		'title' => '_MI_DEBASER_ALLOWPLAYLIST',
		'description' => '_MI_DEBASER_ALLOWPLAYLISTDSC',
		'formtype' => 'group_multi',
		'valuetype' => 'array',
		'default' => array('1' => 1));
	$modversion['config'][] = array(
		'name' => 'owndir',
		'title' => '_MI_DEBASER_OWNDIR',
		'description' => '',
		'formtype' => 'group_multi',
		'valuetype' => 'array',
		'default' => '');
	$modversion['config'][] = array(
		'name' => 'usequota',
		'title' => '_MI_DEBASER_USEQUOTA',
		'description' => '_MI_DEBASER_USEQUOTADSC',
		'formtype' => 'group_multi',
		'valuetype' => 'array',
		'default' => '');
	$modversion['config'][] = array(
		'name' => 'allowdownload',
		'title' => '_MI_DEBASER_ALLOWDOWNLOAD',
		'description' => '_MI_DEBASER_ALLOWDOWNLOADDSC',
		'formtype' => 'group_multi',
		'valuetype' => 'array',
		'default' => array('1' => 1));
	$modversion['config'][] = array(
		'name' => 'candelete',
		'title' => '_MI_DEBASER_CANDELETE',
		'description' => '_MI_DEBASER_CANDELETEDSC',
		'formtype' => 'group_multi',
		'valuetype' => 'array',
		'default' => array('1' => 1));
	$modversion['config'][] = array(
		'name' => 'canedit',
		'title' => '_MI_DEBASER_CANEDIT',
		'description' => '_MI_DEBASER_CANEDITDSC',
		'formtype' => 'group_multi',
		'valuetype' => 'array',
		'default' => array('1' => 1));
	$modversion['config'][] = array(
		'name' => 'indexperpage',
		'title' => '_MI_DEBASER_VIEWLIMIT',
		'description' => '_MI_DEBASER_VIEWLIMITDESC',
		'formtype' => 'select',
		'valuetype' => 'int',
		'default' => 10,
		'options' => array('5' => 5, '10' => 10, '15' => 15, '20' => 20, '25' => 25, '30' => 30, '50' => 50));
	$modversion['config'][] = array(
		'name' => 'indexperpagefront',
		'title' => '_MI_DEBASER_VIEWLIMITFRONT',
		'description' => '_MI_DEBASER_VIEWLIMITFRONTDESC',
		'formtype' => 'select',
		'valuetype' => 'int',
		'default' => 10, 'options' => array('5' => 5, '10' => 10, '15' => 15, '20' => 20, '25' => 25, '30' => 30, '50' => 50));
	$modversion['config'][] = array(
		'name' => 'multilang',
		'title' => '_MI_DEBASER_MULTILANG',
		'description' => '_MI_DEBASER_MULTILANGDESC',
		'formtype' => 'yesno',
		'valuetype' => 'int',
		'default' => '0');
	$modversion['config'][] = array(
		'name' => 'masterlang',
		'title' => '_MI_DEBASER_MASTERLANG',
		'description' => '_MI_DEBASER_MASTERLANGDESC',
		'formtype' => 'textbox',
		'valuetype' => 'text',
		'default' => $xoopsConfig['language']);
	$modversion['config'][] = array(
		'name' => 'innerdisplay',
		'title' => '_MI_DEBASER_INNERDISPLAY',
		'description' => '',
		'formtype' => 'yesno',
		'valuetype' => 'int',
		'default' => '0');
	$modversion['config'][] = array(
		'name' => 'allowembed',
		'title' => '_MI_DEBASER_ALLOWEMBED',
		'description' => '_MI_DEBASER_ALLOWEMBEDDSC',
		'formtype' => 'yesno',
		'valuetype' => 'int',
		'default' => '0');
	$modversion['config'][] = array(
		'name' => 'debaserdiskquota',
		'title' => '_MI_DEBASER_DISKQUOTA',
		'description' => '_MI_DEBASER_DISKQUOTADSC',
		'formtype' => 'textbox',
		'valuetype' => 'text',
		'default' => '0');
	$modversion['config'][] = array(
		'name' => 'debasermaxsize',
		'title' => '_MI_DEBASER_MAXSIZE',
		'description' => '_MI_DEBASER_MAXSIZEDSC',
		'formtype' => 'textbox',
		'valuetype' => 'text',
		'default' => $uploadmax);
	$modversion['config'][] = array(
		'name' => 'debaserflashbatch',
		'title' => '_MI_DEBASER_FLASHBATCH',
		'description' => '_MI_DEBASER_FLASHBATCHDSC',
		'formtype' => 'textbox',
		'valuetype' => 'text',
		'default' => '1');
	$modversion['config'][] = array(
		'name' => 'guestvote',
		'title' => '_MI_DEBASER_GUESTVOTE',
		'description' => '_MI_DEBASER_GUESTVOTEDSC',
		'formtype' => 'yesno',
		'valuetype' => 'int',
		'default' => 0);
	$modversion['config'][] = array(
		'name' => 'guestdownload',
		'title' => '_MI_DEBASER_GUESTDOWNLOAD',
		'description' => '_MI_DEBASER_GUESTDOWNLOADDSC',
		'formtype' => 'yesno',
		'valuetype' => 'int',
		'default' => 0);
	$modversion['config'][] = array(
		'name' => 'shotwidth',
		'title' => '_MI_DEBASER_SHOTWIDTH',
		'description' => '',
		'formtype' => 'textbox',
		'valuetype' => 'int',
		'default' => 140);
	$modversion['config'][] = array(
		'name' => 'shotheight',
		'title' => '_MI_DEBASER_SHOTHEIGHT',
		'description' => '',
		'formtype' => 'textbox',
		'valuetype' => 'int',
		'default' => 79);
	$modversion['config'][] = array(
		'name' => 'catimagefsize',
		'title' => '_MI_DEBASER_CATIMAGEFSIZE',
		'description' => '',
		'formtype' => 'textbox',
		'valuetype' => 'int',
		'default' => 50000);
	$modversion['config'][] = array(
		'name' => 'index_sortby',
		'title' => '_MI_DEBASER_SORTBY',
		'description' => '_MI_DEBASER_SORTBY_DSC',
		'formtype' => 'select',
		'valuetype' => 'text',
		'default' => 'artist',
		'options' => array('_MI_DEBASER_ID' => 'xfid', '_MI_DEBASER_ARTIST' => 'artist', '_MI_DEBASER_TITLE' => 'title'));
	$modversion['config'][] = array(
		'name' => 'index_orderby',
		'title' => '_MI_DEBASER_ORDERBY',
		'description' => '_MI_DEBASER_ORDERBY_DSC',
		'formtype' => 'select',
		'valuetype' => 'text',
		'default' => 'DESC',
		'options' => array('_ASCENDING' => 'ASC', '_DESCENDING' => 'DESC'));
	$modversion['config'][] = array(
		'name' => 'catindex_sortby',
		'title' => '_MI_DEBASER_CATSORTBY',
		'description' => '_MI_DEBASER_CATSORTBY_DSC',
		'formtype' => 'select',
		'valuetype' => 'text',
		'default' => 'genretitle',
		'options' => array('_MI_DEBASER_ID' => 'b.textcatid', '_MI_DEBASER_CATEGORY' => 'b.textcattitle', '_MI_DEBASER_WEIGHT' => 'a.catweight'));
	$modversion['config'][] = array(
		'name' => 'catindex_orderby',
		'title' => '_MI_DEBASER_CATORDERBY',
		'description' => '_MI_DEBASER_CATORDERBY_DSC',
		'formtype' => 'select',
		'valuetype' => 'text',
		'default' => 'DESC',
		'options' => array('_ASCENDING' => 'ASC', '_DESCENDING' => 'DESC'));

	xoops_load('xoopseditorhandler');
	$editor_handler = XoopsEditorHandler::getInstance();

	$modversion['config'][] = array(
		'name' => 'use_wysiwyg',
		'title' => '_MI_DEBASER_FORM_OPTIONS',
		'description' => '_MI_DEBASER_FORM_OPTIONS_DESC',
		'formtype' => 'select',
		'valuetype' => 'text',
		'default' => 'textarea',
		'options' => array_flip($editor_handler->getList()));
	$modversion['config'][] = array(
		'name' => 'autoapprove',
		'title' => '_MI_DEBASER_AUTOAPPROVE',
		'description' => '',
		'formtype' => 'yesno',
		'valuetype' => 'int',
		'default' => 1);
	$modversion['config'][] = array(
		'name' => 'batchapprove',
		'title' => '_MI_DEBASER_BATCHAPPROVE',
		'description' => '',
		'formtype' => 'yesno',
		'valuetype' => 'int',
		'default' => 1);

	if (@ini_get('allow_url_fopen') == '1' && function_exists('curl_init')) $method = 'curl';
	if (@ini_get('allow_url_fopen') == '1' && !function_exists('curl_init')) $method = 'fopen';
	if (@ini_get('allow_url_fopen') != '1' && function_exists('curl_init')) $method = 'curl';
	if (@ini_get('allow_url_fopen') != '1' && !function_exists('curl_init')) $method = 'none';

	$modversion['config'][] = array(
		'name' => 'remotereader',
		'title' => '_MI_DEBASER_REMOTEREADER',
		'description' => '',
		'formtype' => 'textbox',
		'valuetype' => 'text',
		'default' => $method);
	$modversion['config'][] = array(
		'name' => 'brokenreason',
		'title' => '_MI_DEBASER_BROKENREASON',
		'description' => '_MI_DEBASER_BROKENREASONDSC',
		'formtype' => 'textarea',
		'valuetype' => 'text',
		'default' => '_MI_DEBASER_BROK1 _MI_DEBASER_BROK2');
	$modversion['config'][] = array(
		'name'	=> 'nohotlink',
		'title' => '_MI_DEBASER_NOHOTLINK',
		'description' => '_MI_NOHOTLINKDSC',
		'formtype' => 'yesno',
		'valuetype' => 'int',
		'default' => 0);
	$modversion['config'][] = array(
		'name' => 'allowhotlink',
		'title' => '_MI_DEBASER_ALLOWHOTLINK',
		'description' => '_MI_DEBASER_ALLOWHOTLINKDSC',
		'formtype' => 'textarea',
		'valuetype' => 'text',
		'default' => '');
	$modversion['config'][] = array(
		'name' => 'sameauthor',
		'title' => '_MI_DEBASER_SAMEAUTHOR',
		'description' => '_MI_DEBASER_SAMEAUTHORDSC',
		'formtype' => 'textbox',
		'valuetype' => 'text',
		'default' => -1);
	$modversion['config'][] = array(
		'name' => 'simlimit',
		'title' => '_MI_DEBASER_SIMLIMIT',
		'description' => '_MI_DEBASER_SIMLIMITDSC',
		'formtype' => 'textbox',
		'valuetype' => 'text',
		'default' => '50');

	/* Notification */
	$modversion['hasNotification'] = 1;
	$modversion['notification']['lookup_file'] = 'include/notification.inc.php';
	$modversion['notification']['lookup_func'] = 'debaser_notify_iteminfo';

	$modversion['notification']['category'][] = array('name' => 'global', 'title' => _MI_DEBASER_GLOBAL_NOTIFY, 'description' => _MI_DEBASER_GLOBAL_NOTIFYDSC, 'subscribe_from' => array('index.php', 'genre.php', 'singlefile.php'));

	$modversion['notification']['category'][] = array('name' => 'song', 'title' => _MI_DEBASER_SONG_NOTIFY, 'description' => _MI_DEBASER_SONG_NOTIFYDSC, 'subscribe_from' => array('singlefile.php'), 'item_name' => 'xfid');

	$modversion['notification']['event'][] = array('name' => 'new_genre', 'category' => 'global', 'title' => _MI_DEBASER_GENRE_NEWGENRE_NOTIFY, 'caption' => _MI_DEBASER_GENRE_NEWGENRE_NOTIFYCAP, 'description' => _MI_DEBASER_GENRE_NEWGENRE_NOTIFYDSC, 'mail_template' => 'global_newgenre_notify', 'mail_subject' => _MI_DEBASER_GENRE_NEWGENRE_NOTIFYSBJ);

	$modversion['notification']['event'][] = array('name' => 'song_submit', 'category' => 'global', 'admin_only' => 1, 'title' => _MI_DEBASER_NEWSUBMIT_NOTIFY, 'caption' => _MI_DEBASER_NEWSUBMIT_NOTIFYCAP, 'description' => _MI_DEBASER_NEWSUBMIT_NOTIFYDSC, 'mail_template' => 'global_songsubmit_notify', 'mail_subject' => _MI_DEBASER_NEWSUBMIT_NOTIFYSBJ);

	$modversion['notification']['event'][] = array('name' => 'new_song', 'category' => 'global', 'title' => _MI_DEBASER_SONG_NEWSONG_NOTIFY, 'caption' => _MI_DEBASER_SONG_NEWSONG_NOTIFYCAP, 'description' => _MI_DEBASER_SONG_NEWSONG_NOTIFYDSC, 'mail_template' => 'global_newsong_notify', 'mail_subject' => _MI_DEBASER_SONG_NEWSONG_NOTIFYSBJ);

	$modversion['notification']['event'][] = array('name' => 'mimetype_submit', 'category' => 'global', 'admin_only' => 1, 'title' => _MI_DEBASER_MIMETYPESUBMIT_NOTIFY, 'caption' => _MI_DEBASER_MIMETYPESUBMIT_NOTIFYCAP, 'description' => _MI_DEBASER_MIMETYPESUBMIT_NOTIFYDSC, 'mail_template' => 'global_mimetypesubmit_notify', 'mail_subject' => _MI_DEBASER_MIMETYPESUBMIT_NOTIFYSBJ);

	$modversion['notification']['event'][] = array('name' => 'reportbroken', 'category' => 'global', 'admin_only' => 1, 'title' => _MI_DEBASER_REPORTBROKEN_NOTIFY, 'caption' => _MI_DEBASER_REPORTBROKEN_NOTIFYCAP, 'description' => _MI_DEBASER_REPORTBROKEN_NOTIFYDSC, 'mail_template' => 'global_reportbroken_notify', 'mail_subject' => _MI_DEBASER_REPORTBROKEN_NOTIFYSBJ);

?>